### ISSUE TITLE
Docker image build fails

### ISSUE THREAD

**Issue by PabloCastellano** [matlink/gplayweb#23]
```
pablo@siphilis2 ~/src/gplayweb $ docker build -t gplayweb .
Sending build context to Docker daemon  624.6kB
Step 1/20 : FROM ubuntu:16.04
[...]
Step 4/20 : RUN apt-get update && apt-get upgrade -y
 ---> Running in c406adfd126a
[...]
Step 5/20 : RUN apt-get install -y software-properties-common
[...]
Step 6/20 : RUN add-apt-repository ppa:guardianproject/ppa
[...]
Step 7/20 : RUN apt-get update && apt-get install -y 	fdroidserver 	git 	lib32stdc++6 	lib32gcc1 	lib32z1 	lib32ncurses5 	libffi-dev 	libssl-dev 	libjpeg-dev 	python-dev 	python-pip 	python3 	python3-pip 	openjdk-8-jdk 	virtualenv 	wget 	zlib1g-dev
 ---> Running in a7d124757cd6
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://ppa.launchpad.net/guardianproject/ppa/ubuntu xenial InRelease [17.5 kB]
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:6 http://ppa.launchpad.net/guardianproject/ppa/ubuntu xenial/main amd64 Packages [9684 B]
Fetched 27.2 kB in 0s (36.7 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
python3 is already the newest version (3.5.1-3).
python3 set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 fdroidserver : Depends: python3-qrcode but it is not installable
                Recommends: android-sdk but it is not going to be installed
                Recommends: apksigner but it is not installable
                Recommends: opensc but it is not going to be installed
                Recommends: s3cmd but it is not going to be installed
                Recommends: zipalign but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update && apt-get install -y 	fdroidserver 	git 	lib32stdc++6 	lib32gcc1 	lib32z1 	lib32ncurses5 	libffi-dev 	libssl-dev 	libjpeg-dev 	python-dev 	python-pip 	python3 	python3-pip 	openjdk-8-jdk 	virtualenv 	wget 	zlib1g-dev' returned a non-zero code: 100
```

**Comment by PabloCastellano** [comment]
I tried to fix it but could not get it working. Too many different things are failing. If someone wants to continue from my work done, check out https://github.com/PabloCastellano/gplayweb/tree/docker

**Comment by matlink** [comment]
Updating ubuntu to 18.04 worked for me. I'm pushing a new container to docker hub at matlink/gplayweb. Please check & close if resolved :)

**Comment by PabloCastellano** [comment]
Yes, the docker image builds if you change it to use ubuntu 18.04. However gplayweb still does not work. I think we can close this issue and continue fixing it at #24.

```
pablo@siphilis2 ~ $ docker run --rm --name gplayweb -p 127.0.0.1:8888:8888 matlink/gplayweb
error while initializing fdroid repository Traceback (most recent call last):
  File "/usr/bin/fdroid", line 170, in <module>
    main()
  File "/usr/bin/fdroid", line 140, in main
    if system_encoding.lower() not in ('utf-8', 'utf8'):
AttributeError: 'NoneType' object has no attribute 'lower'
```

BTW my PR to fix this crash in fdroidserver has just been merged (https://gitlab.com/fdroid/fdroidserver/merge_requests/671).
