### ISSUE TITLE
Image available in Docker Hub does not work

### ISSUE THREAD

**Issue by PabloCastellano** [matlink/gplayweb#24]
After running `docker run --name gplayweb -p 127.0.0.1:8888:8888 matlink/gplayweb` and loading `http://localhost:8888` I get `500: Internal Server Error`.

The console where docker is running shows

```
ERROR:tornado.application:Uncaught exception GET /?page=list (172.17.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/?page=list', version='HTTP/1.1', remote_ip='172.17.0.1', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0', 'Connection': 'keep-alive', 'Cookie': 'csrftoken=xOuKCjiMF2QnhPLRFYW69xnl4yflqDbnnafhYNFHSOgaqCVA6A7IoslVSR6zrrl8; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; ochaq8ufvkcr=204296a2e197a1b2c75289978d84868b; oc_sessionPassphrase=pcMSrYdWMv9dhhPK7aXsEU6CXfjJjrhKw3JbdyMLhyvVebLMprTeAplwfrl2uGu0zOrizQ32Yu%2FHuUV4w75%2Bn20kBu2aPzl2Slz7hFE6NAh3uAahWZDNRG3dBiIaEUmC; grafana_sess=c7d1953ee0edab26', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/opt/gplayweb/gplayweb", line 41, in get
    self.list()
  File "/opt/gplayweb/gplayweb", line 75, in list
    cached_infos = self.get_infos(results)
  File "/opt/gplayweb/gplayweb", line 93, in get_infos
    details = self.cli.get_bulk_details(apks)
  File "/usr/local/lib/python2.7/dist-packages/gplaycli/gplaycli.py", line 71, in get_bulk_details
    results = self.playstore_api.bulkDetails(list_of_apks)
AttributeError: 'GPlaycli' object has no attribute 'playstore_api'
ERROR:tornado.access:500 GET /?page=list (172.17.0.1) 9.39ms
```

**Comment by PabloCastellano** [comment]
Actually the docker image build fails, see https://github.com/matlink/gplayweb/issues/23 so this should be fixed before.

**Comment by PabloCastellano** [comment]
The docker image builds fine now. 

I tried to fix gplayweb in Docker but could not get it working yet. Too many different things are failing. If someone wants to continue from my work done, check out https://github.com/PabloCastellano/gplayweb/tree/docker
