### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by jmdmahdi** [matlink/gplayweb#7]
I'm trying to install it on windows 
i used git method but i got some errors on installing gplaycli requirements 
how can i fix this issue ?

```
C:\Users\JMDMahdi\Desktop>pip install -r gplaycli/requirements.txt
Collecting requests>=0.12 (from -r gplaycli/requirements.txt (line 1))
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |################################| 471kB 12kB/s
Collecting protobuf>=2.4 (from -r gplaycli/requirements.txt (line 2))
  Downloading protobuf-2.6.1.tar.gz (188kB)
    100% |################################| 188kB 76kB/s
    Complete output from command python setup.py egg_info:

Installed c:\users\jmdmahdi\appdata\local\temp\pip-build-esughn\protobuf\.eggs\google_apputils-0.4.2-py2.7.egg
Searching for pytz>=2010
Reading https://pypi.python.org/simple/pytz/
Best match: pytz 2015.4
Downloading https://pypi.python.org/packages/2.7/p/pytz/pytz-2015.4-py2.7.egg#md5=4698c08f18f5cecba09b7e85d8e9328e
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "c:\users\jmdmahdi\appdata\local\temp\pip-build-esughn\protobuf\setup.py", line 200, in <module>
    "Protocol Buffers are Google's data interchange format.",
  File "C:\Python27\lib\distutils\core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Python27\lib\site-packages\setuptools\dist.py", line 268, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "C:\Python27\lib\site-packages\setuptools\dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 830, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
    return self.obtain(req, installer)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
    return installer(requirement)
  File "C:\Python27\lib\site-packages\setuptools\dist.py", line 380, in fetch_build_egg
    return cmd.easy_install(req)
  File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line 617, in easy_install
    not self.always_copy, self.local_index
  File "C:\Python27\lib\site-packages\setuptools\package_index.py", line 601, in fetch_distribution
    return dist.clone(location=self.download(dist.location, tmpdir))
  File "C:\Python27\lib\site-packages\setuptools\package_index.py", line 517, in download
    found = self._download_url(scheme.group(1), spec, tmpdir)
  File "C:\Python27\lib\site-packages\setuptools\package_index.py", line 758, in _download_url
    return self._attempt_download(url, filename)
  File "C:\Python27\lib\site-packages\setuptools\package_index.py", line 764, in _attempt_download
    headers = self._download_to(url, filename)
  File "C:\Python27\lib\site-packages\setuptools\package_index.py", line 664, in _download_to
    fp = self.open_url(strip_fragment(url))
  File "C:\Python27\lib\site-packages\setuptools\package_index.py", line 714, in open_url
    % (url, v.reason))
distutils.errors.DistutilsError: Download error for https://pypi.python.org/packages/2.7/p/pytz/pytz-2015.4-py2.7.egg#md5=4698c08f18f5cecba09b7e85d8e9328e: [Errno 11002] getaddrinfo failed

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\jmdmahdi\appdata\local\temp\pip-build-esughn\protobuf
```

**Comment by matlink** [comment]
It seems that `pypi.python.org` cannot be resolved by your system. Can you try to access it via a web browser ?

**Comment by jmdmahdi** [comment]
yes i have access to pypi.python.org on browser

**Comment by jmdmahdi** [comment]
i tried to use pip method i got this error 

```
C:\Users\JMDMahdi\Desktop\gplaycli-master\gplayweb>pip install gplayweb
Collecting gplayweb 
  Downloading GPlayWeb-0.1.3.3.tar.gz (141kB)
    100% |################################| 143kB 178kB/s
Collecting gplaycli (from gplayweb)
  Downloading GPlayCli-0.1.2.tar.gz (176kB)
    100% |################################| 180kB 24kB/s
Requirement already satisfied (use --upgrade to upgrade): tornado in c:\python27\lib\site-packages (from gplayweb)
Requirement already satisfied (use --upgrade to upgrade): requests in c:\python27\lib\site-packages (from gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): protobuf in c:\python27\lib\site-packages (from gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): ndg-httpsclient in c:\python27\lib\site-packages (from gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): clint in c:\python27\lib\site-packages (from gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in c:\python27\lib\site-packages (from gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in c:\python27\lib\site-packages (from tornado->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): certifi in c:\python27\lib\site-packages (from tornado->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf->gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): PyOpenSSL in c:\python27\lib\site-packages (from ndg-httpsclient->gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): args in c:\python27\lib\site-packages (from clint->gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in c:\python27\lib\site-packages (from PyOpenSSL->ndg-httpsclient->gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.7 in c:\python27\lib\site-packages (from PyOpenSSL->ndg-httpsclient->gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): enum34 in c:\python27\lib\site-packages (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient->gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in c:\python27\lib\site-packages (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient->gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in c:\python27\lib\site-packages (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient->gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1.0 in c:\python27\lib\site-packages (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient->gplaycli->gplayweb)
Requirement already satisfied (use --upgrade to upgrade): pycparser in c:\python27\lib\site-packages (from cffi>=1.1.0->cryptography>=0.7->PyOpenSSL->ndg-httpsclient->gplaycli->gplayweb)
Installing collected packages: gplaycli, gplayweb
  Running setup.py install for gplaycli
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\jmdmahdi\\appdata\\local\\temp\\pip-build-aono_c\\gplaycli\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\jmdmahdi\appdata\local\temp\pip-mz30im-record\install-record.txt --single-version-externally-managed --compile:
running install
running build
running build_py
creating build
creating build\lib
creating build\lib\ext_libs
creating build\lib\ext_libs\androguard
creating build\lib\ext_libs\androguard\core
creating build\lib\ext_libs\androguard\core\bytecodes
creating build\lib\ext_libs\androguard\core\bytecodes\libdvm
copying ext_libs/androguard/core/bytecodes/libdvm\test_dvm.py -> build\lib\ext_libs/androguard/core/bytecodes/libdvm
copying ext_libs/androguard/core/bytecodes/libdvm\__init__.py -> build\lib\ext_libs/androguard/core/bytecodes/libdvm
copying ext_libs/androguard/core/bytecodes\api_permissions.py -> build\lib\ext_libs/androguard/core/bytecodes
copying ext_libs/androguard/core/bytecodes\apk.py -> build\lib\ext_libs/androguard/core/bytecodes
copying ext_libs/androguard/core/bytecodes\arm.py -> build\lib\ext_libs/androguard/core/bytecodes
copying ext_libs/androguard/core/bytecodes\dvm.py -> build\lib\ext_libs/androguard/core/bytecodes
copying ext_libs/androguard/core/bytecodes\dvm_permissions.py -> build\lib\ext_libs/androguard/core/bytecodes
copying ext_libs/androguard/core/bytecodes\jvm.py -> build\lib\ext_libs/androguard/core/bytecodes
copying ext_libs/androguard/core/bytecodes\jvm_generate.py -> build\lib\ext_libs/androguard/core/bytecodes
copying ext_libs/androguard/core/bytecodes\__init__.py -> build\lib\ext_libs/androguard/core/bytecodes
copying ext_libs/androguard/core\androconf.py -> build\lib\ext_libs/androguard/core
copying ext_libs/androguard/core\bytecode.py -> build\lib\ext_libs/androguard/core
copying ext_libs/androguard/core\__init__.py -> build\lib\ext_libs/androguard/core
copying ext_libs/androguard\__init__.py -> build\lib\ext_libs/androguard
creating build\lib\ext_libs\googleplay_api
copying ext_libs/googleplay_api\config.py -> build\lib\ext_libs/googleplay_api
copying ext_libs/googleplay_api\googleplay.py -> build\lib\ext_libs/googleplay_api
copying ext_libs/googleplay_api\googleplay_pb2.py -> build\lib\ext_libs/googleplay_api
copying ext_libs/googleplay_api\__init__.py -> build\lib\ext_libs/googleplay_api
copying ext_libs\__init__.py -> build\lib\ext_libs
creating build\lib\gplaycli
copying gplaycli\gplaycli.py -> build\lib\gplaycli
copying gplaycli\__init__.py -> build\lib\gplaycli
running build_scripts
creating build\scripts-2.7
copying and adjusting gplaycli\gplaycli -> build\scripts-2.7
running install_lib
creating C:\Python27\Lib\site-packages\ext_libs
creating C:\Python27\Lib\site-packages\ext_libs\androguard
creating C:\Python27\Lib\site-packages\ext_libs\androguard\core
copying build\lib\ext_libs\androguard\core\androconf.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core
copying build\lib\ext_libs\androguard\core\bytecode.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core
creating C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes
copying build\lib\ext_libs\androguard\core\bytecodes\api_permissions.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes
copying build\lib\ext_libs\androguard\core\bytecodes\apk.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes
copying build\lib\ext_libs\androguard\core\bytecodes\arm.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes
copying build\lib\ext_libs\androguard\core\bytecodes\dvm.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes
copying build\lib\ext_libs\androguard\core\bytecodes\dvm_permissions.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes
copying build\lib\ext_libs\androguard\core\bytecodes\jvm.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes
copying build\lib\ext_libs\androguard\core\bytecodes\jvm_generate.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes
creating C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\libdvm
copying build\lib\ext_libs\androguard\core\bytecodes\libdvm\test_dvm.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\libdvm
copying build\lib\ext_libs\androguard\core\bytecodes\libdvm\__init__.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\libdvm
copying build\lib\ext_libs\androguard\core\bytecodes\__init__.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes
copying build\lib\ext_libs\androguard\core\__init__.py -> C:\Python27\Lib\site-packages\ext_libs\androguard\core
copying build\lib\ext_libs\androguard\__init__.py -> C:\Python27\Lib\site-packages\ext_libs\androguard
creating C:\Python27\Lib\site-packages\ext_libs\googleplay_api
copying build\lib\ext_libs\googleplay_api\config.py -> C:\Python27\Lib\site-packages\ext_libs\googleplay_api
copying build\lib\ext_libs\googleplay_api\googleplay.py -> C:\Python27\Lib\site-packages\ext_libs\googleplay_api
copying build\lib\ext_libs\googleplay_api\googleplay_pb2.py -> C:\Python27\Lib\site-packages\ext_libs\googleplay_api
copying build\lib\ext_libs\googleplay_api\__init__.py -> C:\Python27\Lib\site-packages\ext_libs\googleplay_api
copying build\lib\ext_libs\__init__.py -> C:\Python27\Lib\site-packages\ext_libs
creating C:\Python27\Lib\site-packages\gplaycli
copying build\lib\gplaycli\gplaycli.py -> C:\Python27\Lib\site-packages\gplaycli
copying build\lib\gplaycli\__init__.py -> C:\Python27\Lib\site-packages\gplaycli
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\androconf.py to androconf.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecode.py to bytecode.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\api_permissions.py to api_permissions.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\apk.py to apk.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\arm.py to arm.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\dvm.py to dvm.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\dvm_permissions.py to dvm_permissions.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\jvm.py to jvm.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\jvm_generate.py to jvm_generate.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\libdvm\test_dvm.py to test_dvm.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\libdvm\__init__.py to __init__.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\bytecodes\__init__.py to __init__.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\core\__init__.py to __init__.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\androguard\__init__.py to __init__.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\googleplay_api\config.py to config.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\googleplay_api\googleplay.py to googleplay.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\googleplay_api\googleplay_pb2.py to googleplay_pb2.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\googleplay_api\__init__.py to __init__.pyc
byte-compiling C:\Python27\Lib\site-packages\ext_libs\__init__.py to __init__.pyc
byte-compiling C:\Python27\Lib\site-packages\gplaycli\gplaycli.py to gplaycli.pyc
byte-compiling C:\Python27\Lib\site-packages\gplaycli\__init__.py to __init__.pyc
running install_data
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\jmdmahdi\appdata\local\temp\pip-build-aono_c\gplaycli\setup.py", line 29, in <module>
    'pyasn1',
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 61, in run
    return orig.install.run(self)
  File "C:\Python27\lib\distutils\command\install.py", line 575, in run
    self.run_command(cmd_name)
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\install_data.py", line 58, in run
    dir = convert_path(f[0])
  File "C:\Python27\lib\distutils\util.py", line 124, in convert_path
    raise ValueError, "path '%s' cannot be absolute" % pathname
ValueError: path '/etc/gplaycli/' cannot be absolute

----------------------------------------
Command "C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\jmdmahdi\\appdata\\local\\temp\\pip-build-aono_c\\gplaycli\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\jmdmahdi\appdata\local\temp\pip-mz30im-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\jmdmahdi\appdata\local\temp\pip-build-aono_c\gplaycli
```

**Comment by matlink** [comment]
Yes, the config folder cannot be used under Windows, sorry.

**Comment by jmdmahdi** [comment]
i really need that 
which linux distro is more suitable with that ?

**Comment by matlink** [comment]
Any, ubuntu is easily usable 

Le 18 septembre 2015 20:35:22 GMT+02:00, jmdmahdi notifications@github.com a écrit :

> i really need that 
> which linux distro is more suitable with that ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/matlink/gplayweb/issues/7#issuecomment-141530124

## 

Matlink - sysadmin Matlink.fr
